Unicode-encode vim.org text for rethinkdb-v1.13
Summary:
After updating RethinkDB to 1.13 and then running the vim.org scraper, we were
getting this error for every vim.org plugin we scraped:

```
Error scraping vim-fanfou (vimorg_id=4972) from vim.org
Traceback (most recent call last):
  File "/Users/david/code/vim-awesome/tools/scrape/vimorg.py", line 68, in scrape_scripts
    db.plugins.add_scraped_data(plugin)
  File "/Users/david/code/vim-awesome/db/plugins.py", line 500, in add_scraped_data
    insert(updated_plugin, upsert=True)
  File "/Users/david/code/vim-awesome/db/plugins.py", line 176, in insert
    r_conn())
  File "/Users/david/.virtualenv/vim-awesome/lib/python2.7/site-packages/rethinkdb/ast.py", line 75, in run
    return c._start(self, **global_optargs)
  File "/Users/david/.virtualenv/vim-awesome/lib/python2.7/site-packages/rethinkdb/net.py", line 213, in _start
    return self._send_query(query, global_optargs)
  File "/Users/david/.virtualenv/vim-awesome/lib/python2.7/site-packages/rethinkdb/net.py", line 305, in _send_query
    query_str = query.serialize().encode('utf-8')
  File "/Users/david/.virtualenv/vim-awesome/lib/python2.7/site-packages/rethinkdb/net.py", line 36, in serialize
    return json.dumps(res, ensure_ascii=False, allow_nan=False)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 210, in encode
    return ''.join(chunks)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 35: ordinal not in range(128)
```

Test Plan:
Ran `PYTHONPATH=. python tool/scrape/scrape.py -s vim.org 1000`, and verified
the above error is no longer raised for all the plugins we scraped.

Reviewers: xymostech, spicyj

Reviewed By: spicyj

Differential Revision: http://phabricator.benalpert.com/D209