Set Python IO encoding to utf-8 in crontab
Summary:
Otherwise, when we output non-ascii characters and try to pipe that somewhere,
Python does not know which encoding to use, defaults to ascii, and raises a
UnicodeEncodeError.

This fixes errors that look like this in vim:~/logs/cron/github-plugins.log:

```
Scraping plugins from github.com...
Traceback (most recent call last):
  File "/home/vim/vim-awesome/tools/scrape/scrape.py", line 54, in <module>
    scrape_fn(args.number)
  File "/home/vim/vim-awesome/tools/scrape/scrape.py", line 9, in scrape_github_plugins
    github.scrape_plugin_repos(num)
  File "/home/vim/vim-awesome/tools/scrape/github.py", line 243, in scrape_plugin_repos
    print "    scraping %s/%s ..." % (repo_owner, repo_name),
UnicodeEncodeError: 'ascii' codec can't encode characters in position 23-24: ordinal not in range(128)
```

Also disables Python output buffering so that logs are actually comprehensible
and sequential.

Test Plan:
- added the following cronjob to output every minute on the server:
  `python -c 'import sys; print sys.stdout.encoding; print u"\u0411\n"' >> $HOME/testcron.log 2>&1`
- saw that we were getting the same error as we saw in our other cron logs:
  ```
  None
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  UnicodeEncodeError: 'ascii' codec can't encode character u'\u0411' in position 0: ordinal not in range(128)
  ```
- Added "PYTHONIOENCODING=utf-8" to the crontab
- Saw that we were correctly outputting to testcron.log:
  ```
  utf-8
  Б
  ```

Reviewers: xymostech, spicyj

Reviewed By: spicyj

Differential Revision: http://phabricator.benalpert.com/D214